"""Typed contracts for the agentic telecom scenario flow.

The LLM is allowed to produce only ScenarioIntent. Executable schema objects are
compiled from the runtime standards registry.
"""
from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, ConfigDict, Field


class VariableIdea(BaseModel):
    """LLM-created semantic variable idea. It is not executable until the compiler
    assigns a deterministic generator/parameter contract.
    """

    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=2, max_length=120)
    description: str = Field(default="", max_length=500)
    role: Literal[
        "identity", "profile", "event", "transaction", "status",
        "measurement", "metric", "timing", "decision", "configuration", "derived", "other"
    ] = "other"
    grain: Literal["entity", "transaction", "event", "derived"] = "transaction"
    dtype: Literal["string", "integer", "float", "decimal", "boolean", "categorical", "datetime", "date"] = "string"
    depends_on: list[str] = Field(default_factory=list, max_length=8)

class ScenarioIntent(BaseModel):
    """LLM output: intent only, never executable schema semantics."""

    model_config = ConfigDict(extra="forbid")

    # `industry_type` selects the model family; `domain` selects the business/domain slice within it.
    # Keep this provider-safe as a plain string. Gemini structured output can reject
    # unnecessarily restrictive JSON-schema keywords generated by Literal/const.
    # The application normalizes accepted aliases to the canonical ``telecom`` key
    # after the model response is received.
    industry_type: str = "telecom"
    domain: str = "prepaid"
    subdomain: Literal["prepaid", "postpaid", "charging", "usage", "customer", "network", "unknown"] = "prepaid"
    scenario_type: str = ""
    type_of_data: Literal["transactional", "aggregational"] = "transactional"
    entity_key: str = ""
    use_case: str = ""
    requested_entities: list[str] = Field(default_factory=list, max_length=35)
    requested_relationships: list[str] = Field(default_factory=list, max_length=45)
    candidate_variables: list[VariableIdea] = Field(default_factory=list, max_length=35)
    country: str | None = None
    currency: str | None = None
    record_count: int | None = Field(default=None, ge=1, le=5_000_000)
    time_window_days: int | None = Field(default=None, ge=1, le=3650)
    notes: list[str] = Field(default_factory=list, max_length=35)
    ambiguities: list[str] = Field(default_factory=list, max_length=35)




class ResolvedConcept(BaseModel):
    canonical_id: str
    name: str
    source_model: str
    source_references: list[str] = Field(default_factory=list)
    selected_attributes: list[str] = Field(default_factory=list)


class SchemaRelationship(BaseModel):
    source_entity: str
    target_entity: str
    relation: str
    cardinality: str
    required: bool = False
    source_references: list[str] = Field(default_factory=list)


class GeneratedSchemaField(BaseModel):
    name: str
    dtype: str
    description: str = ""
    gen: str
    params: dict[str, Any] = Field(default_factory=dict)
    depends_on: list[str] = Field(default_factory=list)
    nullable: bool = False
    required: bool = False
    formula: str | None = None
    scope: Literal["entity", "transaction", "event", "derived"] = "transaction"
    provenance: dict[str, Any] = Field(default_factory=dict)


class ScenarioSchema(BaseModel):
    domain: str = "telecom"
    subdomain: str = "prepaid"
    applicable_standards: list[dict[str, Any]] = Field(default_factory=list)
    entities: list[ResolvedConcept] = Field(default_factory=list)
    relationships: list[SchemaRelationship] = Field(default_factory=list)
    fields: list[GeneratedSchemaField] = Field(default_factory=list)
    hard_constraints: list[str] = Field(default_factory=list)
    unresolved_items: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class ScenarioProposeRequest(BaseModel):
    """Business-facing JSON contract for agentic scenario proposal.

    The client sends scenario/business metadata only. Technical schema details,
    telecom entities, relationships, generators and constraints are resolved by the backend.
    """

    model_config = ConfigDict(populate_by_name=True, extra="forbid")

    scenario_id: str = Field(alias="scenarioId", min_length=1, max_length=200)
    scenario_type: str = Field(alias="scenarioType", min_length=1, max_length=100)
    industry_type: str = Field(alias="industryType", min_length=1, max_length=100)
    domain: str = Field(min_length=1, max_length=200)
    business_scenario: str = Field(alias="businessScenario", min_length=1, max_length=12000)
    type_of_data: Literal["transactional", "aggregational"] = Field(alias="typeOfData")
    country: str = Field(min_length=1, max_length=20)
    entity_key: str = Field(alias="entityKey", min_length=1, max_length=200)
    use_case: str = Field(alias="useCase", min_length=1, max_length=200)


class ScenarioImportResponse(BaseModel):
    """Shared draft response contract for CSV import and agentic proposal."""
    success: bool = True
    draft_id: str
    scenario_id: str
    requested_scenario_id: str
    journey: str
    description: str
    variables: list[dict]
    field_order: list[str]
    typeOfData: Literal["transactional", "aggregational"]
    entityKey: str | None = None
