"""Glue between the behaviour-pack stack and the existing propose/confirm/generate workflow.

Kept separate from ``concepts`` so the core of ``synth`` has no dependency on the web app's models.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from synth.concepts import Canonicalization, canonicalize
from synth.fill import fill_rates
from synth.pack import BehaviorPack


@dataclass
class PackApplication:
    """Outcome of offering a behaviour pack the merged schema of a proposal."""
    applied: bool
    schema: Any
    variable_sources: dict[str, str]
    raw_persisted_by_name: dict[str, dict[str, Any]]
    report: dict[str, Any]          # always present: what was kept/dropped, or why the pack was skipped


def apply_pack_to_schema(
    schema: Any,
    pack: BehaviorPack,
    variable_sources: dict[str, str],
    raw_persisted_by_name: dict[str, dict[str, Any]],
    *,
    mode: str = "mixed",
    min_fill: float = 0.0,
) -> PackApplication:
    """Collapse a merged ``ScenarioSchema`` onto the pack's concepts - or leave it untouched.

    The pack is applied only when it can serve every curated (DB_RECOMMENDED / USER_SELECTED) variable and
    has a column for every concept it cannot run without. Otherwise the schema is returned unchanged
    (legacy flow) with a report saying exactly why, so a pack never silently removes variables somebody
    curated. DB-owned variable definitions are returned exactly as stored, plus a ``concept`` tag.

    A column that would be empty on nearly every row for this scenario ``mode`` (a value on fewer than ``min_fill``
    of the rows) is left out, because a variable that is null all the time is noise. Only a variable the person
    explicitly selected (USER_SELECTED) is always kept.
    """
    from core.agentic_models import GeneratedSchemaField

    fields = [f.model_dump() for f in schema.fields]
    result = canonicalize(fields, pack, variable_sources)
    base = {"pack_id": pack.pack_id, "pack_version": pack.version}
    if not result.covers:
        return PackApplication(
            False, schema, variable_sources, raw_persisted_by_name,
            {**base, "applied": False, "reason": result.skip_reason(),
             "uncovered_curated": result.uncovered, "missing_required_concepts": result.missing_required},
        )

    _drop_sparse(result, pack, variable_sources, mode, min_fill)
    kept = [GeneratedSchemaField.model_validate(f) for f in result.fields]
    kept_keys = {f.name.strip().casefold() for f in kept}

    sources = {k: v for k, v in variable_sources.items() if k in kept_keys}
    for name in result.added:
        sources[name.strip().casefold()] = "DERIVED"

    raw: dict[str, dict[str, Any]] = {}
    kept_by_key = {str(f["name"]).strip().casefold(): f for f in result.fields}
    for key, definition in raw_persisted_by_name.items():
        if key in kept_keys:
            # The value contract (choices, bounds, nullability) stays exactly as the database stores it.
            # Grain is a business fact of the concept, so the pack's scope overrides a stale stored one.
            raw[key] = {**definition, "concept": kept_by_key[key]["concept"],
                         "scope": kept_by_key[key]["scope"], "primary_timestamp": kept_by_key[key]["primary_timestamp"]}

    report = result.report()
    dropped = report["dropped_by_kind"]
    schema = schema.model_copy(update={
        "fields": kept,
        "hard_constraints": list(schema.hard_constraints) + [
            f"Behaviour pack '{pack.pack_id}' v{pack.version} governs value generation: columns are collapsed "
            "onto business concepts (one column per fact) and generated by a causal journey simulation, "
            "not drawn independently.",
        ],
        "warnings": list(schema.warnings) + result.warnings + [
            f"Behaviour pack '{pack.pack_id}' reduced {result.input_count} candidate columns to {len(kept)} "
            f"({dropped.get('excluded', 0)} out of scope, {dropped.get('duplicate', 0)} duplicates of the same fact, "
            f"{dropped.get('unmapped', 0)} unmapped, {dropped.get('sparse', 0)} empty on nearly every row for this scenario)."
        ],
    })
    return PackApplication(True, schema, sources, raw, {**base, "applied": True, **report})


def _drop_sparse(result: Canonicalization, pack: BehaviorPack, variable_sources: dict[str, str],
                 mode: str, min_fill: float) -> None:
    """Remove columns whose concept is practically always empty in ``mode`` (in place)."""
    if min_fill <= 0:
        return
    fills = fill_rates(pack, mode)
    sources = {str(k).casefold(): str(v).upper() for k, v in variable_sources.items()}
    kept: list[dict[str, Any]] = []
    for column in result.fields:
        cid = str(column.get("concept") or "")
        name = str(column.get("name") or "")
        source = sources.get(name.casefold()) or str(column.get("source") or "").upper()
        concept = pack.concepts.get(cid)
        share = fills.get(cid, 1.0)
        if concept is not None and not concept.required and cid != pack.entity_concept \
                and source != "USER_SELECTED" and share < min_fill:
            result.concept_columns.pop(cid, None)
            result.dropped.append({
                "name": name, "kind": "sparse", "concept": cid, "source": source,
                "reason": f"Carries a value on only {share:.0%} of rows for this scenario type, so it is not "
                          "offered as a variable (select it explicitly if you need it).",
            })
            continue
        kept.append(column)
    result.fields = kept
